Source/TmManager/Controllers/TrademarkController.cs
using Hangfire;
using Kendo.Mvc;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TmManager.Data;
using TmManager.Storage;
using TmManager.Trademarks;

namespace TmManager.Controllers
{
    [Authorize]
    public class TrademarkController : Controller
    {
        private readonly ITrademarkService _trademarkService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IEntityContext _entityContext;
        private IStorage _storage;
        public TrademarkController(ITrademarkService trademarkService, IHttpContextAccessor httpContextAccessor, IEntityContext entityContext, IStorage storage)
        {
            _trademarkService = trademarkService;
            _httpContextAccessor = httpContextAccessor;
            _entityContext = entityContext;
            _storage = storage;
        }
        public ActionResult Index()
        {
            //var result = await _trademarkService.GetTrademarks();
            //return View(result);
            return View();
        }
        public async Task<ActionResult> GetTrademarks()
        {
            var result = await _trademarkService.GetTrademarks();
            return Json(result);
        }
        [HttpPost]
        public IActionResult GetTrademarksForDataTable()
        {
            var draw = Request.Form["draw"].FirstOrDefault();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;

            var result = _trademarkService.GetTrademarksForDataTable(pageSize, skip, sortColumn, sortColumnDirection);
            var jsonData = new { draw = draw, recordsFiltered = result.recordsTotal, recordsTotal = result.recordsTotal, data = result.data };
            return Json(jsonData);
        }
        [HttpGet]
        public async Task<ActionResult> GetTrademarkDetail(Guid id)
        {
            var result = await _trademarkService.GetTrademarkDetail(id);
            return Json(result);
        }
        [HttpGet]
        public async Task<ActionResult> GetClientDetail(string id)
        {
            var result = await _trademarkService.GetClientDetail(id);
            return Json(result);
        }
        [HttpGet]
        public IActionResult NewTrademark()
        {
            return View();
        }
        public IActionResult UploadFile()
        {
            return View();
        }
        public async Task<IActionResult> UploadFileSuccess(string FileName)
        {
            var result = new List<TrademarkImportItemsModel>();
            try
            {
                if (!string.IsNullOrEmpty(FileName))
                {
                    Stream stream = await GetFile(FileName);
                    StreamReader streamReader = new StreamReader(stream);
                    if (streamReader != null)
                    {
                        while (!streamReader.EndOfStream)
                        {
                            var line = await streamReader.ReadLineAsync();
                            var values = line.Split(',');

                            string email = values[0].Trim();
                            string serialNumber = values[1].Trim();
                            if (!string.IsNullOrEmpty(email))
                            {
                                result.Add(new TrademarkImportItemsModel()
                                {
                                    Email = email,
                                    SerialNumber = int.Parse(serialNumber)
                                });
                            }
                            else
                            {
                                return RedirectToAction("UploadFileError");
                            }
                        }
                        //_httpContextAccessor.HttpContext.Session.SetString("UploadFileSession", JsonConvert.SerializeObject(result));
                    }
                }
                TempData["fileName"] = FileName;
            }
            catch (Exception ex)
            {
                Trace.TraceError(ex.ToLogString());
                return RedirectToAction("UploadFileError");
            }
            return View(result);
        }
        public async Task<IActionResult> DuplicateCheck()
        {
            var fileName = string.Empty;
            if (TempData.ContainsKey("fileName"))
            {
                fileName = TempData["fileName"].ToString();
                TempData["fileName"] = fileName;
            }
            var model = new List<TrademarkImportItemsModel>();
            if (!string.IsNullOrEmpty(fileName))
            {
                model = await GetFileData(fileName);
            }
            if (!model.Any())
                RedirectToAction("UploadFile");
            //List<TrademarkImportItemsModel> response = JsonConvert.DeserializeObject<List<TrademarkImportItemsModel>>(jsonString);
            List<long> listTrademarks = model.Select(x => (long)x.SerialNumber).ToList();
            var result = await _trademarkService.GetDuplicateTrademarks(listTrademarks);
            if (result != null)
            {
                foreach (var item in result)
                {
                    var trademark = model.Where(x => x.SerialNumber == item.SerialNumber).FirstOrDefault();
                    trademark.Status = TrademarkStatus.TrademarkInSystem;
                    trademark.TrademarkId = item.Id;
                    trademark.IsDuplicate = true;
                }
            }
            return View(model);
        }
        public async Task<IActionResult> FetchTrademark()
        {
            var result = new TrademarkImportFileModel();
            var fileName = string.Empty;
            if (TempData.ContainsKey("fileName"))
                fileName = TempData["fileName"].ToString();
            if (string.IsNullOrEmpty(fileName))
                return RedirectToAction("UploadFile");
            List<TrademarkImportItemsModel> response = await GetFileData(fileName);
            int r = (new Random()).Next(1000, 9999);
            result.BatchName = fileName;
            result.TrademarkFileItems = response;
            if (result.TrademarkFileItems.Any())
            {
                var results = await _trademarkService.SaveFileRecords(result);
                foreach (var item in result.TrademarkFileItems)
                {
                    if (!item.IsDuplicate)
                    {
                        var jobId = BackgroundJob.Enqueue<ITrademarkService>(x => x.UpdateImportedFilesInfo(item.Id));
                    }
                }
                //var jobId = BackgroundJob.Enqueue<ITrademarkService>(x => x.SaveBatchTrademark(result));
            }
            return View(result);
        }
        [HttpPost]
        public async Task<ActionResult> NewTrademark(SearchTrademarkModel model)
        {
            var results = new TrademarkResponseModel();
            if (ModelState.IsValid)
            {
                results = await _trademarkService.GetTrademark(model.Email, model.SerialNumber.Value.ToString());
                if (results.TrademarkResponse[0].Status == Trademarks.TrademarkStatus.TrademarkSuccess)
                    return View("TrademarkSuccess", results.TrademarkResponse.First());
                else if (results.TrademarkResponse[0].Status == Trademarks.TrademarkStatus.TrademarkDead)
                    return View("TrademarkDead", results.TrademarkResponse.First());
                else if (results.TrademarkResponse[0].Status == Trademarks.TrademarkStatus.TrademarkInSystem)
                    return View("TrademarkInSystem", results.TrademarkResponse.First());
                else if (results.TrademarkResponse[0].Status == Trademarks.TrademarkStatus.TrademarkNotFound)
                    return View("TrademarkNotFound", results.TrademarkResponse.First());
                else if (results.TrademarkResponse[0].Status == Trademarks.TrademarkStatus.TrademarkAttorneyIssue)
                    return View("TrademarkAttorneyIssue", results.TrademarkResponse.First());
                else if (results.TrademarkResponse[0].Status == Trademarks.TrademarkStatus.TrademarkEmailNotFound)
                    return View("TrademarkEmailNotFound", results.TrademarkResponse.First());
                else if (results.TrademarkResponse[0].Status == Trademarks.TrademarkStatus.TrademarkFailed)
                    return View("TrademarkFailed", results.TrademarkResponse.First());
                else if (results.TrademarkResponse[0].Status == Trademarks.TrademarkStatus.SystemError)
                    return View("SystemError", results.TrademarkResponse.First());
            }
            else
            {
                results.Errors = ModelState.Values.SelectMany(e => e.Errors).Select(e => e.ErrorMessage).ToHashSet<string>();
                results.IsSuccess = false;
                return View(model);
            }
            return Json(results);
        }
        [HttpPost]
        public async Task<ActionResult> SaveTrademark(TrademarkResponse model)
        {
            var results = await _trademarkService.SaveTrademark(model.SerialNumber.ToString(), model.FallbackEmail);
            if (results.TrademarkResponse[0].Status == Trademarks.TrademarkStatus.TrademarkLinked)

Source/TmManager/Views/Trademark/FetchTrademark.cshtml
@model TmManager.Trademarks.TrademarkImportFileModel
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_MenuLayout.cshtml";
}

<div class="container">
    <div class="kww-sub-nav">
        <ul>
            <li><a href="/trademark">Trademarks</a></li>
            <li><a href="/trademark/newtrademark">New Trademark</a></li>
            <li class="active"><a href="/trademark/uploadfile">Upload File</a></li>
            <li><a href="/trademark/trademarkretrieved">Trademarks Retrieved</a></li>
            <li><a href="">Archived Files</a></li>
            <li><a href="/trademark/trademarkdeadlist">Dead Trademarks</a></li>
            <li><a href="/trademark/unknownattorney">Unknown Attorney Trademarks </a></li>
        </ul>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h2>Upload File</h2>
        </div>
    </div>
    <form method="post" asp-action="fetchtrademark" asp-controller="trademark" novalidate>
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-12 offset-lg-2 offset-md-2 offset-sm-0">
               
                <div class="text-center">
                    <img class="mb-3" src="~/images/thumsUp.png" />
                    @{
                    }
                    <h3>TM Batch @Model.BatchName has been sent!</h3>
                    <p>The batch contains @Model.TrademarkFileItems.Where(x => x.IsDuplicate == false).Count() trademarks.</p>
                </div>
                <div class="row">
                    @if (Model.TrademarkFileItems.Where(x => x.IsDuplicate == false).Any())
                    {
                        <div class="col-lg-6">
                            <h6>Email</h6>
                        </div>

                        <div class="col-lg-6">
                            <h6>Serial Number</h6>
                        </div>
                    }
                </div>

                @if (Model != null && Model.TrademarkFileItems.Count() > 0)
                {
                    foreach (var item in Model.TrademarkFileItems.Where(x => x.IsDuplicate == false))
                    {

                        <div class="row">
                            <label class="col-lg-6">@item.Email</label>
                            <label class="col-lg-6">@item.SerialNumber</label>
                        </div>
                    }
                }

                <div class="col-sm-12 col-12 text-center my-4">
                    <a href="/trademark/TrademarkRetrieved" role="button" class="btn btn-primary btn-xl">Done</a>
                </div>

                <div class="row">
                    <div class="col-12">
                        <p>NOTE: The system is fetching USPTO data for the above trademarks. This process may take some time. Retrieved trademarks will be available in the "Trademarks Retrieved" page for further processing.</p>
                    </div>
                </div>

            </div>
        </div>
    </form>
</div>
<script>
    $('.kww-main-nav ul').find('li').removeClass('active');
    $('#navTrademarks').parent().addClass('active');
</script>

Source/TmManager/Views/Trademark/NewTrademark.cshtml
@model TmManager.Trademarks.SearchTrademarkModel
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_MenuLayout.cshtml";
}

<div class="modal" id="fetchingDataModel" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">

            <div class="modal-body text-center">
                <i class="fas fa-pulse fa-sync-alt fa-2x"></i>
                <h4>Fetching data</h4>
                <p>Retrieving trademark data from the USPTO database. This may take few seconds.</p>
                <a class="btn btn-secondary text-light" data-dismiss="modal">Cancel Action</a>
            </div>

        </div>
    </div>
</div>

<div class="container">
    <div class="kww-sub-nav">
        <ul>
            <li><a href="/trademark">Trademarks</a></li>
            <li class="active"><a href="/trademark/newtrademark">New Trademark</a></li>
            <li><a href="/trademark/uploadfile">Upload File</a></li>
            <li><a href="/trademark/trademarkretrieved">Trademarks Retrieved</a></li>
            <li><a href="/trademark/trademarkarchieved">Archived Files</a></li>
            <li><a href="/trademark/trademarkdeadlist">Dead Trademarks</a></li>
            <li><a href="/trademark/unknownattorney">Unknown Attorney Trademarks </a></li>
        </ul>
    </div>
    <!--Form-->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="mb-5">Trademarks</h2>

            <div class="row">
                <div class="kww-form-box col-xs" id="trademarkFetch">
                    <h3 class="text-center">Enter New Trademark</h3>
                    <p>Enter the USPTO trademark serial number and the client email in the field below to start the process of entering trademark into the system. The client email will be used only IF an email is not present in the USPTO database.</p>
                    <form method="post" asp-action="NewTrademark" class="formWrapper" asp-controller="Trademark" novalidate>
                        <div class="form-group">
                            <label for="tradeserial">Trademark Serial Number <span class="text-danger">*</span></label>
                            <input type="text" asp-for="SerialNumber" class="form-control" placeholder="88910043">
                            <span asp-validation-for="SerialNumber" class=""></span>
                        </div>
                        <div class="form-group">
                            <label for="email">Email <span class="text-danger">*</span></label>
                            <input type="email" asp-for="Email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="user@email.com">
                            <span asp-validation-for="Email" class=""></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Fetch Trademark from USPTO" role="button" class="btn btn-primary btn-xl" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    $('.kww-main-nav ul').find('li').removeClass('active');
    $('#navTrademarks').parent().addClass('active');

    function OnBeginTrademark() {
        $('#fetchingDataModel').modal('show');
    };

    function OnTrademarkSaved(res) {
        if (res.isSuccess) {
            $('.trademarkGeneral').addClass('d-none');
            $('#trademarkLinked').removeClass('d-none');
        }
    }

    function OnSuccessTrademark(res) {
        $('#fetchingDataModel').modal('hide');
        $('.trademarkGeneral').addClass('d-none');
        console.log(res);
        if (res.isSuccess) {
            var name = res.trademarkResponse[0].name;
            var clientName = res.trademarkResponse[0].clientName;
            var serialNumber = res.trademarkResponse[0].serialNumber;
            var primaryEmail = res.trademarkResponse[0].primaryEmail;
            var primaryPhone = res.trademarkResponse[0].primaryPhone;
            var streetAddress = res.trademarkResponse[0].streetAddress;
            var city = res.trademarkResponse[0].city;
            var state = res.trademarkResponse[0].state;
            var zipCode = res.trademarkResponse[0].zipCode;
            var country = res.trademarkResponse[0].country;
            var statusnumber = res.trademarkResponse[0].statusNumber;
            var statusdescription = res.trademarkResponse[0].statusDescription;

            $('.lblName').html(name);
            $('.lblClientName').html(clientName);
            $('.lblPrimaryEmail').html(primaryEmail);
            $('.lblPrimaryPhone').html(primaryPhone);
            $('.lblStreetAddress').html(streetAddress);
            $('.lblCity').html(city);
            $('.lblState').html(state);
            $('.lblZipCode').html(zipCode);
            $('.lblCountry').html(country);
            $('.lblSerialNumber').html(serialNumber);

            if (statusnumber == 2) {
                $('#trademarkSuccess').removeClass('d-none');
            } else if (statusnumber == 10) {
                $('#trademarkDead').removeClass('d-none');
            }
        }
        else if (res.errors != undefined && res.errors.length > 0) {
            //$('#trademarkSearch').addClass('d-none');
            //$('#trademarkNotFound').removeClass('d-none');
            if (res.errors[0] == "Email field is required" || res.errors[0] == "Serial Number field is required") {
                $('#errorDiv').html(res.errors[0]);
            } else if (res.errors[0] == "Record already exists") {
                $('.lblSerialNumber').html(res.trademarkResponse[0].serialNumber);
                $('#trademarkAlreadyInSystem').removeClass('d-none');
            }
        }
    }
</script>

Source/TmManager/Views/Trademark/SystemError.cshtml
@model TmManager.Trademarks.TrademarkResponse
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_MenuLayout.cshtml";
}

<div class="container">
    <div class="kww-sub-nav">
        <ul>
            <li><a href="/trademark">Trademarks</a></li>
            <li class="active"><a href="/trademark/newtrademark">New Trademark</a></li>
            <li><a href="/trademark/uploadfile">Upload File</a></li>
            <li><a href="/trademark/trademarkretrieved">Trademarks Retrieved</a></li>
            <li><a href="/trademark/trademarkarchieved">Archived Files</a></li>
            <li><a href="/trademark/trademarkdeadlist">Dead Trademarks</a></li>
            <li><a href="/trademark/unknownattorney">Unknown Attorney Trademarks </a></li>
        </ul>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h2>New Trademarks</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12 offset-lg-2 offset-md-2 offset-sm-0 text-center">
            <input type="hidden" id="SerialNumber" name="SerialNumber" value="@Model.SerialNumber" />
            <img src="~/images/Alerticon.png" />
            <h3>System Error!</h3>
            <p>Failed to add trademark with @Model.SerialNumber in the system.</p>
            <a href="/trademark/newtrademark" role="button" class="btn btn-primary btn-xl">Try again</a>
        </div>
    </div>
</div>

Source/TmManager/Views/Trademark/TrademarkAccountCreated.cshtml
@model TmManager.Trademarks.TrademarkResponse
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_MenuLayout.cshtml";
}
<div class="container">
    <div class="kww-sub-nav">
        <ul>
            <li><a href="/trademark">Trademarks</a></li>
            <li class="active"><a href="/trademark/newtrademark">New Trademark</a></li>
            <li><a href="/trademark/uploadfile">Upload File</a></li>
            <li><a href="/trademark/trademarkretrieved">Trademarks Retrieved</a></li>
            <li><a href="/trademark/trademarkarchieved">Archived Files</a></li>
            <li><a href="/trademark/trademarkdeadlist">Dead Trademarks</a></li>
            <li><a href="/trademark/unknownattorney">Unknown Attorney Trademarks </a></li>
        </ul>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h2>Trademarks</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12 offset-lg-2 offset-md-2 offset-sm-0">
            <input type="hidden" id="SerialNumber" name="SerialNumber" value="@Model.SerialNumber" />
            <div class="text-center">
                <img class="mb-3" src="~/images/Icon.Add.png" />
                 <h3>New Account Created</h3>
                <p>A new account was created using the email @Model.Email. Trademark with the serial number @Model.SerialNumber is now linked to this account.</p>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>Client Name</strong></label>
                <label class="col-6">@Model.ClientName</label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>Primary Email</strong></label>
                <label class="col-6">@Model.PrimaryEmail</label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>Primary Phone</strong></label>
                <label class="col-6 lblPrimaryPhone"></label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>Street Address</strong></label>
                <label class="col-6">@Model.StreetAddress</label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>City</strong></label>
                <label class="col-6">@Model.City</label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>State/Province</strong></label>
                <label class="col-6">@Model.State</label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>Zip Code</strong></label>
                <label class="col-6">@Model.ZipCode</label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>Country</strong></label>
                <label class="col-6">@Model.Country</label>
            </div>

            <div class="row mx-3 action-buttons">
                <div class="col-12 text-center">
                    <a href="/trademark/newtrademark" role="button" class="btn btn-primary btn-xl">Continue</a>
                </div>
            </div>

        </div>
    </div>
</div>

Source/TmManager/Views/Trademark/TrademarkArchieved.cshtml
@using Kendo.Mvc.UI
@model TmManager.Trademarks.TrademarkResponseForKendo
@{ 
    ViewData["Title"] = "Trademark";
    Layout = "~/Views/Shared/_MenuLayout.cshtml";
}


<!--Form-->
<div class="container">
    <div class="kww-sub-nav">
        <ul>
            <li><a href="/trademark">Trademarks</a></li>
            <li><a href="/trademark/newtrademark">New Trademark</a></li>
            <li><a href="/trademark/uploadfile">Upload File</a></li>
            <li><a href="/trademark/trademarkretrieved">Trademarks Retrieved</a></li>
            <li class="active"><a href="/trademark/trademarkarchieved">Archived Files</a></li>
            <li><a href="/trademark/trademarkdeadlist">Dead Trademarks</a></li>
            <li><a href="/trademark/unknownattorney">Unknown Attorney Trademarks </a></li>
        </ul>
    </div>
    <div class="row">
        <div class="col-lg-12 mb-4">
            <h2>Trademarks</h2>
        </div>
    </div>
    <!--Grid-->
    <h3 class="my-3 text-center d-block">View Archived Trademark Import Batches (90 days max)</h3>
    
    <div class="row d-flex align-items-end">
        <div class="col-lg-4">
            <div class="dateSelectorW">
                <label class="m-0">Start Date <span class="text-danger">*</span></label>
                @Html.Kendo().DatePickerFor(model => model.StartDate).Format("MM/dd/yyyy").Value(DateTime.Now.AddDays(-90).Date).HtmlAttributes(new { @type = "text" })
            </div>
        </div>
        <div class="col-lg-4">
            <div class="dateSelectorW">
                <label class="m-0">End Date <span class="text-danger">*</span></label>
                @Html.Kendo().DatePickerFor(model => model.EndDate).Format("MM/dd/yyyy").Value(DateTime.Now.Date).HtmlAttributes(new { @type = "text" })
            </div>
        </div>
        <div class="col-lg-4">
            <input type="button" id="btnSearch" role="button" class="btn btn-primary btn-xl mt-5" value="Search for Trademark(s)" />
        </div>

    </div>
    <div class="k-overflow-grid trademarkretrieved">
        @(Html.Kendo().Grid<TmManager.Trademarks.TrademarkArchievedReportModel>
                    ()
                    .Name("Grid")
                    .EnableCustomBinding(true)
                    .Columns(columns =>
                    {
                        columns.Bound(c => c.Name).Title("Batch Name").Width("30%");
                        columns.Bound(c => c.Count).Title("Trademark Name").Width("30%");
                        columns.Bound(c => c.Created).Format("{0:yyyy.MM.dd HH:mm:ss}").Title("Date Imported").Width("30%"); ;
                        columns.Bound(c => c.Id).Title("Detail").ClientTemplate("<a class='kww-filled-btn-sm' href='/trademark/trademarkarchiveditem?id=#=data.Id#&batchName=#=data.Name#'>View Details</a>").Width("10%");
                    })
                    .Pageable(pager => pager
                    .Input(false)
                    .Numeric(true)
                    .Info(true)
                    .PreviousNext(true)
                    .Refresh(true)
                    )
                    .AutoBind(true)
                    .Sortable()
                    .DataSource(dataSource => dataSource
                    .Ajax()
                    .PageSize(10)
                    .Read(read => read.Action("TrademarkArchieved", "Trademark"))
                    .ServerOperation(true)
                 ))
    </div>
</div>
<script>
    $('.kww-main-nav ul').find('li').removeClass('active');
    $('#navTrademarks').parent().addClass('active');

    function GetByDate(fromdate, todate) {
        var MyGrid = $("#Grid").data("kendoGrid");
        var arrayFilter = [];
        arrayFilter.push({ field: "StartDate", operator: "ge", value: fromdate });
        arrayFilter.push({ field: "EndDate", operator: "le", value: todate });
        MyGrid.dataSource.filter(arrayFilter);
    }

    $('#btnSearch').click(function () {
        var FromDate = $('#StartDate').val();
        var ToDate = $('#EndDate').val();
        if (FromDate == "" || FromDate == null || ToDate == "" || ToDate == null) {
            $('#ServerError').html("Start and End date can not be empty");
        }
        else if (new Date(FromDate) > new Date(ToDate)) {
            $('#ServerError').html("Start date should not be greater than end date");
        }
        else {
            $('#divFilters').addClass('d-none');
            GetByDate(FromDate, ToDate);
        }
    });

</script>

Source/TmManager/Views/Trademark/TrademarkAttorneyIssueOnSave.cshtml
@model TmManager.Trademarks.TrademarkResponse
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_MenuLayout.cshtml";
}
<div class="container">
    <div class="kww-sub-nav">
        <ul>
            <li class="active"><a href="/trademark">Trademarks</a></li>
            <li><a href="/trademark/newtrademark">New Trademark</a></li>
            <li><a href="/trademark/uploadfile">Upload File</a></li>
            <li><a href="/trademark/trademarkretrieved">Trademarks Retrieved</a></li>
            <li><a href="/trademark/trademarkarchieved">Archived Files</a></li>
            <li><a href="/trademark/trademarkdeadlist">Dead Trademarks</a></li>
            <li><a href="/trademark/unknownattorney">Unknown Attorney Trademarks </a></li>
        </ul>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h2>Trademarks</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12 offset-lg-2 offset-md-2 offset-sm-0">
            <input type="hidden" id="SerialNumber" name="SerialNumber" value="@Model.SerialNumber" />
            <input type="hidden" id="FallbackEmail" name="FallbackEmail" value="@Model.FallbackEmail" />
            <div class="text-center">
                <img class="mb-3" src="~/images/redalert.png" />
                <h3>Attorney of record issue!</h3>
                <p>Trademark with the serial number @Model.SerialNumber was found, But it is not listed in your attorney of records list.</p>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>Client Name</strong></label>
                <label class="col-6">@Model.ClientName</label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>Primary Email</strong></label>
                <label class="col-6">@Model.PrimaryEmail</label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>Primary Phone</strong></label>
                <label class="col-6 lblPrimaryPhone"></label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>Street Address</strong></label>
                <label class="col-6">@Model.StreetAddress</label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>City</strong></label>
                <label class="col-6">@Model.City</label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>State/Province</strong></label>
                <label class="col-6">@Model.State</label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>Zip Code</strong></label>
                <label class="col-6">@Model.ZipCode</label>
            </div>
            <div class="form-group row">
                <label class="col-6"><strong>Country</strong></label>
                <label class="col-6">@Model.Country</label>
            </div>

            <div class="row mx-3 action-buttons">
                <div class="col-12 text-center">
                    <a href="/trademark/newtrademark" role="button" class="btn btn-primary btn-xl">Continue</a>
                </div>
            </div>

        </div>
    </div>
</div>